app_name: EasyMSR
usb_app_name: EasyMSR USB
title: MSR605/MSRX6BT App for Deftun/Misiri/Postech
app_subtitle: iOS/Android app for MSRX6/MSRX6BT via Bluetooth
usb_app_subtitle: Android app for MSR605x via USB
ios_download: https://apps.apple.com/us/app/easymsr-pro/id6483249260
android_download: https://play.google.com/store/apps/details?id=com.easymsr
usb_android_download: https://play.google.com/store/apps/details?id=net.easymsr.usb
app_id: 6483249260
email: msr@tcool.ltd
app_icon: /assets/icon.png
favicon: /assets/icon.png
canonical_url: https://www.easymsr.net

made_by: TCool LTD.

links:
  - title: AppStore Connect Widget
    url: https://ac-widget.xyz

app_description: |
    EasyMSR is an iOS/Android app for MSR605X/MSRX6/MSRX6BT. It can control the MSR reader/writer via Bluetooth or USB.    

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
