app_name: EasyMSR
app_subtitle: iOS/Android app for MSRX6BT device via Bluetooth
ios_download: https://apps.apple.com/us/app/easymsr-pro/id6483249260
android_download: https://play.google.com/store/apps/details?id=com.easymsr
app_id: 6483249260
email: msr@tcool.ltd
app_icon: /assets/icon.png
favicon: /assets/icon.png

made_by: TCool LTD.

links:
  - title: AppStore Connect Widget
    url: https://ac-widget.xyz

app_description: |
    EasyMSR is an iOS/Android app to control the MSRX6BT device via Bluetooth.

    ## Features

    1. Support READ/WRITE operations
    1. Support 3 tracks
    2. Support Lo-co/Hi-co (Low Coercivity/High Coercivity) magnetic stripe cards
    3. Support ISO data format
    

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
