app_name: EasyMSR
usb_app_name: EasyMSR USB
title: MSR605/MSRX6BT App for Deftun/Tnaive/Misiri/Postech
app_subtitle: iOS/Android app for MSRX6/MSRX6BT via Bluetooth
app_description: EasyMSR can control MSR605X/MSRX6/MSRX6BT via Bluetooth or USB. It's compatible with Deftun/Tnaive/Misiri/Postech.
usb_app_subtitle: Android app for MSR605x via USB
ios_download: https://apps.apple.com/app/apple-store/id6483249260?pt=126665557&ct=easymsr.net&mt=8
android_download: https://play.google.com/store/apps/details?id=com.easymsr&referrer=utm_source%3Deasymsrnet%26utm_medium%3Dorganic
usb_android_download: https://play.google.com/store/apps/details?id=net.easymsr.usb&referrer=utm_source%3Deasymsrnet%26utm_medium%3Dorganic
msr880_android_download: https://play.google.com/store/apps/details?id=net.easymsr.osayde.usb&referrer=utm_source%3Deasymsrnet%26utm_medium%3Dorganic
btmsr_android_download: https://play.google.com/store/apps/details?id=ltd.tcool.btmsr&referrer=utm_source%3Deasymsrnet%26utm_medium%3Dorganic
app_id: 6483249260
email: msr@tcool.ltd
app_icon: /assets/icon.png
favicon: /assets/icon.png
canonical_url: https://www.easymsr.net

made_by: TCool LTD.

links:
  - title: AppStore Connect Widget
    url: https://ac-widget.xyz

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - .gitignore
  - node_modules

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "assets/screenshots"
    values:
      screenshot: true
